// Auto-generated by Prometheus Studio
// Level management exports

export { LEVEL_REGISTRY, TOTAL_LEVELS, getLevelByOrder, getNextLevel, isLevelUnlocked } from './level-registry';

// Level file paths for dynamic loading
export const LEVEL_PATHS = {
  3: '/levels/level-003.json'
};

export function getLevelPath(levelOrder: number): string | undefined {
  return LEVEL_PATHS[levelOrder];
}
