// Auto-generated by Prometheus Studio
// Do not edit this file manually - it will be overwritten

export interface LevelRegistryEntry {
  id: number;
  filename: string;
  displayName: string;
  description: string;
  unlockRequirements: {
    completedLevels: number[];
    minScore: number;
  };
}

export const LEVEL_REGISTRY: LevelRegistryEntry[] = [
  {
    id: 3,
    filename: 'level-003.json',
    displayName: 'Level 3',
    description: '',
    unlockRequirements: {
      completedLevels: [2],
      minScore: 0
    }
  }
];

export const TOTAL_LEVELS = 1;

export function getLevelByOrder(order: number): LevelRegistryEntry | undefined {
  return LEVEL_REGISTRY.find(level => level.id === order);
}

export function getNextLevel(currentOrder: number): LevelRegistryEntry | undefined {
  return LEVEL_REGISTRY.find(level => level.id === currentOrder + 1);
}

export function isLevelUnlocked(levelOrder: number, completedLevels: number[], playerScore: number): boolean {
  const level = getLevelByOrder(levelOrder);
  if (!level) return false;
  
  // Check if all required levels are completed
  const requiredCompleted = level.unlockRequirements.completedLevels.every(
    requiredLevel => completedLevels.includes(requiredLevel)
  );
  
  // Check minimum score requirement
  const scoreRequirementMet = playerScore >= level.unlockRequirements.minScore;
  
  return requiredCompleted && scoreRequirementMet;
}
