// Auto-generated by Prometheus Studio
// Do not edit this file manually - it will be overwritten

export interface LevelRegistryEntry {
  id: number;
  filename: string;
  displayName: string;
  description: string;
  unlockRequirements: {
    completedLevels: number[];
    minScore: number;
  };
}

export const LEVEL_REGISTRY: LevelRegistryEntry[] = [
  {
    id: 1,
    filename: 'level-001.json',
    displayName: '',
    description: '',
    unlockRequirements: {
      completedLevels: [],
      minScore: 0
    }
  },
  {
    id: 2,
    filename: 'level-002.json',
    displayName: '',
    description: '',
    unlockRequirements: {
      completedLevels: [1],
      minScore: 0
    }
  },
  {
    id: 3,
    filename: 'level-003.json',
    displayName: '',
    description: '',
    unlockRequirements: {
      completedLevels: [2],
      minScore: 0
    }
  },
  {
    id: 4,
    filename: 'level-004.json',
    displayName: '',
    description: '',
    unlockRequirements: {
      completedLevels: [3],
      minScore: 0
    }
  },
  {
    id: 5,
    filename: 'level-005.json',
    displayName: '',
    description: '',
    unlockRequirements: {
      completedLevels: [4],
      minScore: 0
    }
  },
  {
    id: 6,
    filename: 'level-006.json',
    displayName: 'test1_ Level 1',
    description: '',
    unlockRequirements: {
      completedLevels: [5],
      minScore: 0
    }
  },
  {
    id: 7,
    filename: 'level-007.json',
    displayName: 'Anna',
    description: '',
    unlockRequirements: {
      completedLevels: [6],
      minScore: 0
    }
  },
  {
    id: 8,
    filename: 'level-008.json',
    displayName: '',
    description: '',
    unlockRequirements: {
      completedLevels: [7],
      minScore: 0
    }
  },
  {
    id: 9,
    filename: 'level-009.json',
    displayName: '',
    description: '',
    unlockRequirements: {
      completedLevels: [8],
      minScore: 0
    }
  }
];

export const TOTAL_LEVELS = 9;

export function getLevelByOrder(order: number): LevelRegistryEntry | undefined {
  return LEVEL_REGISTRY.find(level => level.id === order);
}

export function getNextLevel(currentOrder: number): LevelRegistryEntry | undefined {
  return LEVEL_REGISTRY.find(level => level.id === currentOrder + 1);
}

export function isLevelUnlocked(levelOrder: number, completedLevels: number[], playerScore: number): boolean {
  const level = getLevelByOrder(levelOrder);
  if (!level) return false;
  
  // Check if all required levels are completed
  const requiredCompleted = level.unlockRequirements.completedLevels.every(
    requiredLevel => completedLevels.includes(requiredLevel)
  );
  
  // Check minimum score requirement
  const scoreRequirementMet = playerScore >= level.unlockRequirements.minScore;
  
  return requiredCompleted && scoreRequirementMet;
}
